Challenges/jedihomeworld/force-app/main/default/objects/Contact/fields/Total_Payment_Amount_this_Month__c.field-meta.xml
<CustomField>
    <fullName>Total_Payment_Amount_this_Month__c</fullName>
    <label>Total Payment Amount this Month</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Challenges/jedihomeworld/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

jedihomeworld/force-app/main/default/objects/Payment__c/fields/Void__c.field-meta.xml
<CustomField>
    <fullName>Void__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Void</label>
    <type>Checkbox</type>
</CustomField>

Challenges/jedihomeworld/force-app/main/default/classes/contactHelper.cls
public with sharing class contactHelper {

    public static void updatePayments(Set<id>contactSetId){
        updatePayments(new List<id>(contactSetId));
    }

    public static void updatePayments(List<id> contactListId){

        //List of contact and payments
        Map<id,Contact> contactMap = new Map<id,Contact>([SELECT id, Name, (SELECT id, Name, Amount__c, Payment_Date__c FROM Payments__r WHERE Payment_Date__c = THIS_MONTH AND Void__c = False) FROM Contact WHERE id in:contactListId]);

        List<Contact> returnContacts = new List<Contact>();

        //loop over contacts
        for (Contact cont : contactMap.values()){
            system.debug(cont.Name);
            cont.Total_Payment_Amount_this_Month__c = 0;

            //loop over filtered payments
            for (Payment__c pay : cont.Payments__r){
                cont.Total_Payment_Amount_this_Month__c += pay.Amount__c;
            }

            //add to list of updated contacts
            returnContacts.add(cont);
        }

        update returnContacts;
    }
}