jedihomeworld/force-app/main/default/objects/Account/fields/Number_of_Non_void_Payments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Non_void_Payments__c</fullName>
    <label>Number of Non-void Payments</label>
    <summaryFilterItems>
        <field>Payment__c.Void__c</field>
        <operation>equals</operation>
        <value>False</value>
    </summaryFilterItems>
    <summaryForeignKey>Payment__c.Account__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Challenges/jedihomeworld/force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <displayFormat>P-{0}</displayFormat>
        <label>Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Challenges/jedihomeworld/force-app/main/default/objects/Payment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

jedihomeworld/force-app/main/default/objects/Payment__c/fields/Void__c.field-meta.xml
<CustomField>
    <fullName>Void__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Void</label>
    <type>Checkbox</type>
</CustomField>

jedihomeworld/force-app/main/default/classes/AccountPaymentController.cls
public with sharing class AccountPaymentController {
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccountList(){
        return [SELECT Id, Name, Number_of_Non_void_Payments__c, AnnualRevenue FROM Account];
    }

    @AuraEnabled
    public static void voidPayments(String accountId){
        List<Payment__c> returnPaymentList = new List<Payment__c>();

        for (Payment__c pay : [SELECT id FROM Payment__c WHERE Account__c = :accountId]){
            pay.Void__c = true;
            returnPaymentList.add(pay);
        }
        update returnPaymentList;
    }

    //test method use for learning how apex refresh and pass parameters work
    // @AuraEnabled
    // public static void updateAccount(String accountId){
    //     Account acc = [SELECT id, AnnualRevenue FROM Account WHERE id = :accountId];
    //     if (acc.AnnualRevenue == null){
    //         acc.AnnualRevenue = 1;
    //     } else {
    //         acc.AnnualRevenue += 1;
    //     }
    //     update acc;
    // }
}